### PR TITLE
Add a note on the result

### PR DESCRIPTION
**Pull request by Grummfy**
Hello,
I just added a note, to be clearer on the type of json structure is accepted.

### CODE REVIEW

**Comment by bflad** [comment]
Hi @Grummfy 👋  Thank you for submitting this! Can you clarify what other types of maps would be possible?

**Comment by Grummfy** [comment]
At my knowledge, there is no other type than key-value

**Comment by bflad** [comment]
Thanks so much, @Grummfy 👍  Since the term map already implies a key-value data structure in JSON, I'm going to leave this description as-is.

Future changes such as #76 will also remove this particular restriction, so it is likely this description will be changing as part of that effort.

**Comment by Grummfy** [comment]
well @bflad a value in json can be anything, not only scalar value, so a nested object is also a value... this make everything confusing

**Pull request closed without merging**
