### PR TITLE
Provide additional "sensitive" data source

### PR DESCRIPTION
**Pull request by zhimsel**
This PR adds the `external_sensitive` data source which masks the query and result. This is functionally identical to its non-sensitive counterpart.

Also, a minor README fix.

Confirm that tests pass as expected. Also tested functionally with internal resources.

This closes https://github.com/hashicorp/terraform-provider-external/issues/44

### CODE REVIEW

**Comment by zhimsel** [comment]
I'm sure there's a more elegant way to do this, but I figure simply having a separate data source that's set to sensitive is easier to implement.

**Comment by marshallford** [comment]
Any movement on this?

**Comment by lscheidler** [comment]
@bflad any plans to merge this pull request or to implement a similar feature? Would love it to have a sensitive result, preventing showing the output of the result.

**Comment by jbcom** [comment]
Anything I can do to tell this along? This would make a huge difference in plan output since we use external for very long, complex merges of data that result in massive base64 strings.

**Comment by bflad** [comment]
Hi folks 👋  Terraform CLI versions 0.15 and later implement generic sensitive value handling that solves this problem at the Terraform configuration level, outside of any provider changes.

For example:

- Input variables can be configured with `sensitive = true`, see also: https://www.terraform.io/language/values/variables#suppressing-values-in-cli-output
- Output variables can be configured with `sensitive = true`, see also: https://www.terraform.io/language/values/outputs#sensitive-suppressing-values-in-cli-output
- Values can be marked as sensitive with the `sensitive()` function, see also: https://www.terraform.io/language/functions/sensitive

To show this in practice, check out this Terraform configuration:

```terraform
terraform {
  required_providers {
    external = {
      source  = "hashicorp/external"
      version = "2.1.1"
    }
  }

  required_version = ">= 0.15.0"
}

data "external" "test" {
  program = ["jq", "."]
  query = {
    "some-key" = "some-value"
  }
}

locals {
  sensitive_result = sensitive(data.external.test.result)
}

output "nonsensitive" {
  value = data.external.test.result
}

output "sensitive_function" {
  # Without sensitive = true, Terraform CLI will error when receiving sensitive value
  sensitive = true
  value     = sensitive(data.external.test.result)
}

output "sensitive_local" {
  # Without sensitive = true, Terraform CLI will error when receiving sensitive value
  sensitive = true
  value     = local.sensitive_result
}

output "sensitive_output" {
  sensitive = true
  value     = data.external.test.result
}
```

When applied:

```console
$ terraform apply

Changes to Outputs:
  + nonsensitive       = {
      + "some-key" = "some-value"
    }
  + sensitive_function = (sensitive value)
  + sensitive_local    = (sensitive value)
  + sensitive_output   = (sensitive value)

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes


Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

nonsensitive = tomap({
  "some-key" = "some-value"
})
sensitive_function = <sensitive>
sensitive_local = <sensitive>
sensitive_output = <sensitive>
```

While this may not fully obviate the need for a computed attribute in the data source that is always marked sensitive (since this functionality can not be toggled conditionally by the provider due to some protocol limitations, see also https://github.com/hashicorp/terraform-plugin-sdk/issues/736), this functionality should be able to cover most use cases.

To that end, _if_ there were going to be changes made to the provider, the preferred implementation in this case would instead be a new `Sensitive: true` result attribute on the existing data source, rather than introducing an entirely separate data source that performs the exact same logic. That implementation may not be accepted however, since there is generic sensitive value handling now available outside of the provider itself.

Rather than leave this pull request open when it likely would not be merged in its current state, I'm going to close this for now. If the above suggestion is separately resubmitted, it can be re-evaluated. Thank you for submitting this, @zhimsel!

**Comment by zhimsel** [comment]
Hm... I could have _sworn_ that changes in data source values showed up in plans/diffs. Upon testing, that isn't the case, and using `sensitive()` works for that purpose.

I still think it may be useful to be able to mark the _entire_ data source object as sensitive (as you suggested). I may work on implementing that in the future and re-submit a PR.

**Pull request closed without merging**
